### ISSUE TITLE
findSupportFragmentById()

### ISSUE THREAD

**Issue by highwater** [cuplv/droidel#23]
Hi, I used the latest version of Droidel but unfortunately this error keeps coming up

Exception in thread "Thread-2" java.lang.AssertionError: assertion failed: Couldn't compile stub file /Users/shin/Documents/Project/output/com.spring.bird.game2048plus/bin/droidel_classes/generatedharness/GeneratedAndroidHarness
	at scala.Predef$.assert(Predef.scala:179)
	at edu.colorado.droidel.codegen.AndroidStubGenerator$class.writeAndCompileStub(AndroidStubGenerator.scala:59)
	at edu.colorado.droidel.codegen.SimpleAndroidHarnessGenerator.writeAndCompileStub(SimpleAndroidHarnessGenerator.scala:11)
	at edu.colorado.droidel.codegen.SimpleAndroidHarnessGenerator.generateHarness(SimpleAndroidHarnessGenerator.scala:81)
	at edu.colorado.droidel.driver.AndroidAppTransformer.generateFrameworkDependentHarness(AndroidAppTransformer.scala:623)
	at edu.colorado.droidel.driver.AndroidAppTransformer.transformApp(AndroidAppTransformer.scala:734)
	at id.apkcompare.ApkCompare$5.run(ApkCompare.java:294)
	at java.lang.Thread.run(Thread.java:745)
warning: [options] bootstrap class path not set in conjunction with -source 1.6
/Users/shin/Documents/Project/output/com.spring.bird.game2048plus/bin/droidel_classes/generatedharness/GeneratedAndroidHarness.java:5: error: generatedharness.GeneratedAndroidHarness.AppStubs is not abstract and does not override abstract method findSupportFragmentById(int) in droidelhelpers.DroidelStubs
  static final class AppStubs
               ^
/Users/shin/Documents/Project/output/com.spring.bird.game2048plus/bin/droidel_classes/generatedharness/GeneratedAndroidHarness.java:27: error: method does not override or implement a method from a supertype
    @Override
    ^
/Users/shin/Documents/Project/output/com.spring.bird.game2048plus/bin/droidel_classes/generatedharness/GeneratedAndroidHarness.java:31: error: method does not override or implement a method from a supertype
    @Override
    ^
/Users/shin/Documents/Project/output/com.spring.bird.game2048plus/bin/droidel_classes/generatedharness/GeneratedAndroidHarness.java:35: error: method does not override or implement a method from a supertype
    @Override
    ^
/Users/shin/Documents/Project/output/com.spring.bird.game2048plus/bin/droidel_classes/generatedharness/GeneratedAndroidHarness.java:39: error: method does not override or implement a method from a supertype
    @Override
    ^

**Comment by sblackshear** [comment]
Hi Coraline,
  I would guess that the problem is using a version of Android that is too new. Unfortunately, Droidel's stubs are a bit specialized to a particular version of Android (4.4.2) and may not work correctly or even compile for other versions.
